name: Build and Deploy Docker App to Azure Web App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: oidc

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/awaken-ai:latest .

      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.AZURE_ACR_NAME }}
          
      - name: Push image to ACR
        run: |
          docker push ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/awaken-ai:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --docker-custom-image-name ${{ secrets.AZURE_ACR_NAME }}.azurecr.io/awaken-ai:latest \
            --docker-registry-server-url https://${{ secrets.AZURE_ACR_NAME }}.azurecr.io
