name: Build, Push Docker to ACR, and Deploy to App Service

on:
  push:
    branches:
      - main

permissions:
  id-token: write     # Required for OIDC login to Azure
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name:  Azure Login via OIDC
        uses: azure/login@v2
        with:
          client-id: 62510ec0-f0cb-41d3-988e-96ed2461dd4b
          tenant-id: 23f2001443dsstudyiitmac.onmicrosoft.com
          subscription-id: 3e73c002-7f97-440d-9ed0-523aae89c0ab
          auth-type: oidc

      - name:  Log in to Azure Container Registry
        run: |
          az acr login --name awakenAIRegistry

      - name:  Build Docker Image
        run: |
          docker build -t awakenairegistry.azurecr.io/awakenai:latest .

      - name:  Push Docker Image to ACR
        run: |
          docker push awakenairegistry.azurecr.io/awakenai:latest

      - name:  Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: Awaken-AI
          images: awakenairegistry.azurecr.io/awakenai:latest
